### ISSUE TITLE
Room class seperation

### ISSUE THREAD

**Issue by wxyz-abcd** [wxyz-abcd/node-haxball#16]
We need to seperate Room class into two different classes: HostRoom and ClientRoom. Room class will become the base class for these subclasses. This is necessary to make writing code easier for people, and writing documentation easier for us.

**Comment by wxyz-abcd** [comment]
This has to be done after getting rid of the roomObj hook.

**Comment by Nellty** [comment]
This is a must have, for sure. Aren't `RoomHost` and `RoomClient` names would be better?

**Comment by wxyz-abcd** [comment]
Names don't really matter that much. :) After almost 3 months, this issue is still open... The main features are still not completely finished, so I cannot focus on these smaller issues. :)

**Comment by wxyz-abcd** [comment]
It turns out that this already existed within the game engine itself, but with a slightly different logic. So I did not need to re-do it,..
