### ISSUE TITLE
Input Control is bugged causes desynchronization

### ISSUE THREAD

**Issue by hxgd1** [wxyz-abcd/node-haxball#27]
The plugin modifyPlayerInput.js have some bugs. 

Joined Player ID: 1
Host Player ID: 0

**Problem:** If command `!input 1 0` is used, both players are frozen. 
**Solution:** Must check internal logic

**Problem:** While problem 1 is happening, if you open chat and then leave the room the host player (ID 0 in this case) has chat indicator open forever.
**Solution:**  Must check internal logic

**Problem:** If you put a non-existing player ID to command it is causing desynchronization. 
**Solution:** Before executing the command check for the ID to see if it exists or not.

**Comment by wxyz-abcd** [comment]
The chat indicator problem must be linked to the custom signal that I created myself to communicate between custom clients. The freezing problem? No idea yet. But I will find out.

**Comment by wxyz-abcd** [comment]
I checked it on my website, it is working correctly, no desync happens at all. I don't understand how it did not work in your case.

**Comment by wxyz-abcd** [comment]
I'm closing this issue since I've tested it enough to know that this issue does not exist anymore. If you still have it, open another issue.
