### ISSUE TITLE
Question about Browser Usage

### ISSUE THREAD

**Issue by guguxh** [wxyz-abcd/node-haxball#30]
![image](https://user-images.githubusercontent.com/61206153/205935320-41e70ea7-5251-46df-a5ff-dfccc2ea6d72.png)
![image](https://user-images.githubusercontent.com/61206153/205935358-4963f524-e2eb-4f2a-b982-82cce0e68778.png)
When I setup the overrides, and turn on, the game doesn't work properly, like in screenshots.

**Comment by wxyz-abcd** [comment]
I'm moving this to discussions, since this is not an issue but a question.
