### ISSUE TITLE
Websocket connection always failing?

### ISSUE THREAD

**Issue by tomasrivero** [wxyz-abcd/node-haxball#58]
![image](https://user-images.githubusercontent.com/31349354/222932717-40d0638c-827c-4dcb-9806-2e6279b650da.png)

I was able to build the project, and bypass the CORS restriction by using moseif's extension. But for some reason after adding a proper token, the connection to the websocket fails.

**Comment by wxyz-abcd** [comment]
I do not know abut that extension, but you can use the haxballOriginModifier extension in this repo. I'm using it without any problems.

**Comment by tomasrivero** [comment]
Worked like a charm. I was having issues finding that specific extension. Appreciate it.
