### ISSUE TITLE
feature request: aimbot plugin

### ISSUE THREAD

**Issue by xumical** [wxyz-abcd/node-haxball#62]
there used to be a script that would draw arrows for the ball? if i recall correctly. example: https://youtu.be/il5Anf_PrP0?t=175

is this available with this client? or can it be added?

thanks : )

**Comment by wxyz-abcd** [comment]
Thanks for the request. I will start adding all requests very soon. Currently I'm just a little too busy with documentation & typescript. I'll be listing all requests in discord server and here, and then do them one by one.

**Comment by wxyz-abcd** [comment]
Done for now.
