### ISSUE TITLE
error while joining rooms simultenously

### ISSUE THREAD

**Issue by 0x00214131812049** [wxyz-abcd/node-haxball#9]
https://github.com/wxyz-abcd/node-haxball/blob/a175ec7f6ba0ca98fe44e48ee259d3a8d76bf9bb/src/index.js#L6031
TypeError: Cannot read properties of undefined (reading 'appendChild')

When i tried [joinNRandomRooms.js](https://github.com/wxyz-abcd/node-haxball/blob/main/examples/api_structure/joinNRandomRooms.js), got this error. Also, it triggers at start of script immediately

**Comment by wxyz-abcd** [comment]
We have to wait for "ready" event before we can join a room:

_haxBall.on("ready", () => {
  _haxBall.joinRoom({
  ...
  });
});
